name: mmoCore
version: ${releaseVersion} b${buildNumber}
description: mmoCore provides the common code for all mmoMinecraft plugins to use.
author: Rycochet <rycochet@rycochet.com>
website: 

main: mmo.Core.MMOCore
depend: [Spout]

commands:
    mmoset:
        description: Sets config options for mmoMinecraft plugins
        permission: mmocore.set
        usage: /mmoset <plugin> <path.to.option> <value>
    mmoupdate:
        description: Update all mmoMinecraft plugins
        aliases: [mmoupdate2]
        permission: mmocore.update
        usage: /mmoupdate [force]

permissions:
    mmocore.*:
        description: Access to mmoCore commands
        default: op
        children:
            mmocore.set: true
            mmocore.update: true
    mmocore.set:
        description: Allows you to edit mmoMinecraft module settings
        default: false
    mmocore.update:
        description: Allows you to update all mmoMinecraft plugins
        default: false
